# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #BFF4EE
background         #020011
cursor             #AB97A6

active_tab_foreground     #020011
active_tab_background     #BFF4EE
inactive_tab_foreground   #BFF4EE
inactive_tab_background   #020011

active_border_color   #BFF4EE
inactive_border_color #020011
bell_border_color     #911B4A

color0      #030014
color1		#911B4A
color2		#911B4A
color3		#7F7517
color4		#B81B2E
color5		#16855A
color6		#10A896
color7		#9BE7DE
color8		#6CA29B
color9		#AA1C54
color10		#AA1C54
color11		#857910
color12		#E0162E
color13		#119762
color14		#16E0C8
color15		#9BE7DE
