# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(212227)
$foreground = rgb(E4EBE8)
$color0 = rgb(4C4D54)
$color1 = rgb(623D12)
$color2 = rgb(614916)
$color3 = rgb(1D5F9E)
$color4 = rgb(905123)
$color5 = rgb(9E5C1D)
$color6 = rgb(28955B)
$color7 = rgb(D1DBD5)
$color8 = rgb(929995)
$color9 = rgb(6F4512)
$color10 = rgb(6E5117)
$color11 = rgb(1C6EBA)
$color12 = rgb(A05623)
$color13 = rgb(B66519)
$color14 = rgb(36C777)
$color15 = rgb(D1DBD5)
