# Variables
$Wallpaper = $HOME/HyprLand/temp/current_wallpaper.png
$Avatar = $HOME//HyprLand/temp/current_avatar.png

# Background
background {
   blur_passes = 6
   blur_size = 8
    monitor =
    path = $Wallpaper
    brightness = 0.8172
}

# TIME (Large clock at top)
# TIME
label {
    monitor =
    text = cmd[update:1000] echo $(date +"%I:%M %p")
    font_size = 175
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 0, -30
    halign = center
    valign = top
    z-index = 999
}

# Date
label {
    monitor =
    text = cmd[update:1000] echo -e -n "╭─────────────  " && echo -n -e $(date +"%Y-%m-%d") && echo -e -n "  ─────────────╮"
    color = rgba(255, 255, 255, 1)
    font_size = 30
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 0, -30
    halign = center
    valign = top
    z-index = 999
}

# Day
label {
    monitor =
    text = cmd[update:1000] echo -e -n "╰────────────── " && echo -n -e $(date +"%A" | cut -c 1-10) && echo -e -n " ──────────────╯"
    color = rgba(255, 255, 255, 1)
    font_size = 30
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 0, -305
    halign = center
    valign = top
    z-index = 999
}

# Avatar (Centered)
image {
    monitor =
    path = $Avatar
    size = 200
    rounding = -1 # Circular
    border_size = 0
    border_color = rgba(255, 255, 255, 0.3)
    position = 0, 100
    halign = center
    valign = center
    z-index = 999
}
 # Greeting (below Avatar)
label {
    monitor =
    text = cmd[update:60000] echo "$(shuf -n 1 /home/kevo/HyprLand/temp/greetings.txt)"
    font_size = 30
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    color =rgba(255, 192, 203, 1.0)
    position = 0, -30
    halign = center
    valign = center
    z-index = 999
}

# Input-Field (Below Avatar)
input-field {
    monitor =
    size = 300, 55
    dots_size = 0.3
    dots_spacing = 0.1
    dots_center = true
    dots_rounding = -1
    outer_color = rgba(255, 255, 255, 0.3)
    inner_color = rgba(255, 255, 255, 0.3)
    fade_on_empty = false
    placeholder_text = <b>パスワード入力</b>
    hide_input = false
    rounding = 20
    fail_color = rgb(255, 123, 123)
    fail_text = <b>パスワードの誤り</b>
    position = 0, -360
    halign = center
    valign = center
    z-index = 999
}

# Music (Bottom-ish)
label {
    monitor =
    text = cmd[update:1000] echo "$(/home/kevo/HyprLand/userScripts/musicPlayer.sh)"
    color = 	rgba(128, 128, 128, 1.0)
    font_size = 18
    font_family = JetBrains Mono Nerd Font Mono Bold
    position = 0, 165
    halign = center
    valign = bottom
    z-index = 999
}

# Message/Quotes (Folded for wrapping)
label {
    monitor =
    # The 'fold' command ensures the quote doesn't go off-screen
    text = cmd[update:60000] echo "$(shuf -n 1 /home/kevo/HyprLand/temp/quotes.txt | fold -s -w 50)"
    color = rgba(135, 206, 235, 1.0)
    font_size = 22
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    text_align = center
    position = 0, 35
    halign = center
    valign = bottom
    z-index = 999
}
