# Enable IPC so you can still manually change if you want
ipc = on

# NEW BLOCK SYNTAX
wallpaper {
    monitor =
    path = ~/Pictures/wallpapers
    # Options for auto-changing
    timeout = 300
    order = random
    fit_mode = cover
}

# No more manual 'preload' lines needed for directories!
