[Audio]
Volume=70

[General]
ColorScheme=Breeze Dark
FileDialogLastLocation=file:///home/kev0/Videos/Men In Black 3 (2012) %5B1080p%5D
LastPlayedFile=file:///home/kvnx/Downloads/From.S03.1080p.x265-ELiTE/From.S03E04.1080p.x265-ELiTE.mkv

[Playback]
OpenLastPlayedFile=true
PauseWhileMinimized=true
RestoreFilePosition=true

[Playlist]
OpenWithSingleClick=true
RememberState=true
