[Shortcuts]
playNextAction=PgDown
playPreviousAction=PgUp
playbackSpeedResetAction=
restartPlaybackAction=Backspace
seekBackwardBigAction=
seekForwardBigAction=
seekNextChapterAction=
seekPreviousChapterAction=
volumeDownAction=Down
volumeUpAction=Up
