# ~/.config/foot/foot.ini
[main]
font=monospace:size=11
pad=15x15
selection-target=both

[key-bindings]
# Unbound so Ctrl+C cancels commands
clipboard-copy=Control+c
clipboard-paste=Control+v

[cursor]
style=underline
blink=yes
underline-thickness=5
blink-rate=400 

[colors-dark]
alpha=0.7
background=212227
foreground=E4EBE8

# Selection Highlight Colors (Pink)
selection-background=905123
selection-foreground=212227

cursor=212227 905123

## Normal colors
regular0=4C4D54
regular1=623D12
regular2=614916
regular3=1D5F9E
regular4=905123
regular5=9E5C1D
regular6=28955B
regular7=D1DBD5

## Bright colors
bright0=929995
bright1=6F4512
bright2=6E5117
bright3=1C6EBA
bright4=A05623
bright5=B66519
bright6=36C777
bright7=D1DBD5
